version: "3.1"
services:
  server:
    image: mysql:8.0
    restart: always
    networks:
      - bridge
    ports:
      - 8080:8080
    environment:
      - MYSQL_ROOT_PASSWORD=
    command: --skip-initialize-insecure
    volumes:
      - ./src/database/index.js:/docker-entrypoint-index

networks:
  bridge:

volumes:
  db_data: